name: pytorch
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.5.0=h7ea286d_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - bayesian-optimization=1.4.3=pyhd8ed1ab_0
  - blas=1.0=openblas
  - bottleneck=1.3.7=py38hbda83bc_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py38h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.2.25=hca03da5_0
  - cairo=1.16.0=h302bd0f_5
  - certifi=2024.8.30=py38hca03da5_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cma=4.0.0=pyhecae5ae_0
  - colorama=0.4.6=py38hca03da5_0
  - contourpy=1.0.5=py38h525c30c_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.4=h313beb8_0
  - ffmpeg=5.1.2=gpl_hf318d42_106
  - filelock=3.13.1=py38hca03da5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=hee714a5_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py38h80987f9_0
  - freetype=2.12.1=hadb7bae_2
  - gdk-pixbuf=2.42.10=h80987f9_1
  - geos=3.12.2=h00cdb27_1
  - gettext=0.21.0=h13f89a0_1
  - giflib=5.2.2=h80987f9_0
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py38h8c48613_0
  - gnutls=3.7.8=h9f1a10d_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=6.0.0=hd7af201_1
  - hdf5=1.14.0=nompi_h6b85c65_102
  - icu=72.1=he12128b_0
  - idna=3.7=py38hca03da5_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - importlib_resources=6.4.0=py38hca03da5_0
  - jasper=2.0.33=hc3cd1e9_1
  - jinja2=3.1.4=py38hca03da5_0
  - joblib=1.4.2=py38hca03da5_0
  - jpeg=9e=h80987f9_3
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyterthemes=0.20.0=py_1
  - kiwisolver=1.4.4=py38h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a28f6b_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - lesscpy=0.15.1=pyhd8ed1ab_0
  - libaec=1.1.3=h313beb8_0
  - libblas=3.9.0=1_h2ec9a88_netlib
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcblas=3.9.0=1_h9886b1c_netlib
  - libcurl=8.9.1=h3e2b118_0
  - libcxx=20.1.1=ha82da77_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.17=h0d3ecfb_2
  - libidn2=2.3.4=h80987f9_0
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - liblapack=3.9.0=1_h9886b1c_netlib
  - liblapacke=3.9.0=1_h9886b1c_netlib
  - libllvm14=14.0.6=hf6e71e7_1
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libopencv=4.7.0=py38h427f6f2_1
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.21.12=hb5ab8b9_0
  - libsqlite=3.45.2=h091b4b1_0
  - libssh2=1.11.1=h3e2b118_0
  - libtasn1=4.19.0=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libunistring=0.9.10=h1a28f6b_0
  - libvpx=1.11.0=hc377ac9_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.10.4=h2aff0a6_0
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=14.0.6=hc6e5704_0
  - llvmlite=0.41.0=py38h514c7bf_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py38h80987f9_0
  - matplotlib=3.7.2=py38hca03da5_0
  - matplotlib-base=3.7.2=py38h46d7db6_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py38hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nettle=3.8.1=h63371fa_1
  - networkx=3.1=py38hca03da5_0
  - nevergrad=1.0.1=pyhd8ed1ab_1
  - nlopt=2.7.1=h313beb8_0
  - numba=0.58.1=py38h313beb8_0
  - numexpr=2.8.4=py38h79ee842_1
  - numpy=1.24.3=py38h1398885_0
  - numpy-base=1.24.3=py38h90707a3_0
  - opencv=4.7.0=py38h150bfb4_1
  - openh264=2.3.1=hb7217d7_2
  - openjpeg=2.5.2=h54b8e55_0
  - openslide=3.4.1=ha537b0c_6
  - openslide-python=1.3.1=py38h336bac9_1
  - openssl=3.4.0=h39f12f2_0
  - p11-kit=0.24.1=h29577a5_0
  - packaging=24.1=py38hca03da5_0
  - pandas=2.0.3=py38h46d7db6_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py38h80987f9_0
  - pip=24.2=py38hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - platformdirs=3.10.0=py38hca03da5_0
  - plotly=5.24.1=py38h33ce5c2_0
  - ply=3.11=pyhd8ed1ab_2
  - pooch=1.7.0=py38hca03da5_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - pthread-stubs=0.3=h1a28f6b_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-opencv=4.7.0=py38hfbcc8b7_1
  - pybobyqa=1.4.1=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pynndescent=0.5.10=py38hca03da5_0
  - pyparsing=3.0.9=py38hca03da5_0
  - pysocks=1.7.1=py38hca03da5_0
  - python=3.8.16=h3ba56d0_1_cpython
  - python-dateutil=2.9.0post0=py38hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.8=5_cp38
  - pytorch=2.4.1=py3.8_0
  - pytz=2024.1=py38hca03da5_0
  - pyyaml=6.0.2=py38h80987f9_0
  - readline=8.2=h1a28f6b_0
  - requests=2.32.3=py38hca03da5_0
  - scikit-learn=1.3.0=py38h46d7db6_1
  - scipy=1.10.1=py38h9d039d2_1
  - seaborn=0.13.2=py38hca03da5_0
  - setuptools=75.1.0=py38hca03da5_0
  - shapely=2.0.6=py38hda5ed4e_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.2=hf2abe2d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - svt-av1=1.4.1=h7ea286d_0
  - sympy=1.13.2=py38hca03da5_0
  - tbb=2021.8.0=h48ca7d4_0
  - tenacity=9.0.0=py38hca03da5_0
  - threadpoolctl=3.5.0=py38h33ce5c2_0
  - tk=8.6.13=h5083fa2_1
  - torchaudio=2.4.1=py38_cpu
  - torchvision=0.20.0=py38_cpu
  - tornado=6.4.1=py38h80987f9_0
  - tqdm=4.66.5=py38h33ce5c2_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.11.0=py38hca03da5_0
  - umap-learn=0.5.6=py38h10201cd_1
  - unicodedata2=15.1.0=py38h80987f9_0
  - urllib3=2.2.3=py38hca03da5_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py38hca03da5_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zipp=3.20.2=py38hca03da5_0
  - zlib=1.2.13=hfb2fe0b_6
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - anyio==4.5.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==24.3.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.17.1
      - comm==0.2.2
      - debugpy==1.8.11
      - defusedxml==0.7.1
      - dropbox==12.0.2
      - exceptiongroup==1.2.2
      - fastjsonschema==2.21.1
      - fqdn==1.5.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - ipykernel==6.29.5
      - ipython==8.12.3
      - isoduration==20.11.0
      - jedi==0.19.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - mistune==3.0.2
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pkgutil-resolve-name==1.3.10
      - prometheus-client==0.21.1
      - psutil==6.1.0
      - pycparser==2.22
      - python-json-logger==3.2.1
      - pyzmq==26.2.0
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.1
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - stone==3.3.1
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.2.1
      - types-python-dateutil==2.9.0.20241206
      - uri-template==1.3.0
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
prefix: /opt/anaconda3/envs/pytorch
